# Generated by Django 5.0.6 on 2024-06-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_usuario_email'),
    ]

    operations = [
    ]
