# Generated by Django 5.0.6 on 2024-06-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alojamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='imagenes',
        ),
        migrations.CreateModel(
            name='ImagenAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='alojamientos/')),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myapp.alojamiento')),
            ],
        ),
    ]
