# Generated by Django 5.0.6 on 2024-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_imagenusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mostrar_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ImagenUsuario',
        ),
    ]
